### ISSUE TITLE
Подключить eslint-airbnb-config

### ISSUE THREAD

**Issue by MikeDevice** [yandex-praktikum/client-server-template-with-vite#21]
Нередко встречаю очено опасный код у студендов, по типу инлайновых ифаков:

```js
someVariable && doAction()
```

вместо
```js
if (someVariable) {
  doAction()
}
```

и всяко разного ещё. И приходится объяснять, что это плохо, что есть общепринятые подходы и тд. и тп.

Мне кажется, подключив такой конфиг, у студентов будет вырабатываться правильный стиль написания кода.

сс @HellSquirrel

**Comment by HellSquirrel** [comment]
Привет, спасибо за предложение, но я бы хотела оставить проверки минимальными. Если хочется, можно договориться и отдельно подключить конфиг для вашей команды

**Comment by HellSquirrel** [comment]
Закрою эту issue, но если есть принципиальные возражения feel free переоткрыть
